import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "admin@admin.com",
      password: bcrypt.hashSync("123"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@user.com",
      password: bcrypt.hashSync("123"),
      isAdmin: false,
    },
  ],

  products: [
    {
      slug: "free-shirt",
      name: "Free shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      slug: "slim-shirt",
      name: "Slim shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 180,
      brand: "Reebok",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      slug: "golf-pants",
      name: "Golf pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 70,
      brand: "BrownPants",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      slug: "basketball-pants",
      name: "Basckeball pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      slug: "classic-pants",
      name: "Classic Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Another popular pants",
    },
  ],
};

export default data;
